apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  labels:
    app: alpine
  annotations:
    kubernetes.io/change-cause: "profile"
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: alpine
        image: suraj435/profile-custom:v1
        ports:
        - containerPort: 80
~
